function createfigure(X1, Y1, title)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-Nov-2017 00:47:42

% Create figure
figure1 = figure('Name','Tiempos');

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Marker','o');

% Create xlabel
xlabel({'Cantidad de hebras'},'HorizontalAlignment','center','FontSize',11);

% Create ylabel
ylabel({'Tiempo (s)'},'HorizontalAlignment','center','FontSize',11);

% Create title
title(title,'FontSize',11);

